In [1]:
import numpy as np

In [2]:
list=[1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16]

In [3]:
a=np.array(list)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16])

In [4]:
a**2

array([  1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121, 144, 169,
       196, 225, 256], dtype=int32)

In [5]:
b=np.array(a+100)
b

array([101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112, 113,
       114, 115, 116])

In [6]:
c=np.array(a,dtype=np.int16,ndmin=2)
c

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16]],
      dtype=int16)

In [7]:
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16])

In [8]:
np.arange(1,10,3)   #1+3=4,4+3=7  aise no generate hoga.

array([1, 4, 7])

In [9]:
c=np.arange(1,10,0.5)
c

array([1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. , 5.5, 6. , 6.5, 7. ,
       7.5, 8. , 8.5, 9. , 9.5])

In [10]:
np.array(range(1,10))

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [11]:
np.array(range(1,10,2))

array([1, 3, 5, 7, 9])

In [12]:
np.linspace(1,10,4)

array([ 1.,  4.,  7., 10.])

In [13]:
9/2

4.5

In [14]:
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16])

In [15]:
d=np.linspace(1,10,20)
d

array([ 1.        ,  1.47368421,  1.94736842,  2.42105263,  2.89473684,
        3.36842105,  3.84210526,  4.31578947,  4.78947368,  5.26315789,
        5.73684211,  6.21052632,  6.68421053,  7.15789474,  7.63157895,
        8.10526316,  8.57894737,  9.05263158,  9.52631579, 10.        ])

In [16]:
9/19

0.47368421052631576

In [17]:
c=np.linspace(1,10,50)  # used in regression
c

array([ 1.        ,  1.18367347,  1.36734694,  1.55102041,  1.73469388,
        1.91836735,  2.10204082,  2.28571429,  2.46938776,  2.65306122,
        2.83673469,  3.02040816,  3.20408163,  3.3877551 ,  3.57142857,
        3.75510204,  3.93877551,  4.12244898,  4.30612245,  4.48979592,
        4.67346939,  4.85714286,  5.04081633,  5.2244898 ,  5.40816327,
        5.59183673,  5.7755102 ,  5.95918367,  6.14285714,  6.32653061,
        6.51020408,  6.69387755,  6.87755102,  7.06122449,  7.24489796,
        7.42857143,  7.6122449 ,  7.79591837,  7.97959184,  8.16326531,
        8.34693878,  8.53061224,  8.71428571,  8.89795918,  9.08163265,
        9.26530612,  9.44897959,  9.63265306,  9.81632653, 10.        ])

In [18]:
9/49

0.1836734693877551

In [19]:
f=np.logspace(1,2)  # logspace means power by default base 10 hoga
f

array([ 10.        ,  10.48113134,  10.98541142,  11.51395399,
        12.06792641,  12.64855217,  13.25711366,  13.89495494,
        14.56348478,  15.26417967,  15.9985872 ,  16.76832937,
        17.57510625,  18.42069969,  19.30697729,  20.23589648,
        21.20950888,  22.22996483,  23.29951811,  24.42053095,
        25.59547923,  26.82695795,  28.11768698,  29.47051703,
        30.88843596,  32.37457543,  33.93221772,  35.56480306,
        37.2759372 ,  39.06939937,  40.94915062,  42.9193426 ,
        44.98432669,  47.14866363,  49.41713361,  51.79474679,
        54.28675439,  56.89866029,  59.63623317,  62.50551925,
        65.51285569,  68.6648845 ,  71.9685673 ,  75.43120063,
        79.06043211,  82.86427729,  86.85113738,  91.0298178 ,
        95.40954763, 100.        ])

In [20]:
f=np.logspace(2.0,3.0,num=5)  # start 10^2  end 10^3  base 10
f  

array([ 100.        ,  177.827941  ,  316.22776602,  562.34132519,
       1000.        ])

In [21]:
f.shape

(5,)

In [22]:
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16])

In [23]:
e=np.logspace(1,10,10)   # base e

In [24]:
e

array([1.e+01, 1.e+02, 1.e+03, 1.e+04, 1.e+05, 1.e+06, 1.e+07, 1.e+08,
       1.e+09, 1.e+10])

In [25]:
e=np.logspace(1,10,10,base=2)
e

array([   2.,    4.,    8.,   16.,   32.,   64.,  128.,  256.,  512.,
       1024.])

In [26]:
# 10**d

In [27]:
f=np.empty((5))
f

array([ 100.        ,  177.827941  ,  316.22776602,  562.34132519,
       1000.        ])

In [28]:
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16])

In [29]:
g=np.empty((4,4))
print(g)
print(g.ndim)

[[6.23042070e-307 4.67296746e-307 1.69121096e-306 6.23058707e-307]
 [2.22522597e-306 1.33511969e-306 1.37962320e-306 9.34604358e-307]
 [9.79101082e-307 1.78020576e-306 1.69119873e-306 2.22522868e-306]
 [1.24611809e-306 8.06632139e-308 1.60221208e-306 2.29178686e-312]]
2


In [30]:
f=np.empty((5,1))
f

array([[ 100.        ],
       [ 177.827941  ],
       [ 316.22776602],
       [ 562.34132519],
       [1000.        ]])

In [34]:
np.empty((4,4))

array([[6.23042070e-307, 4.67296746e-307, 1.69121096e-306,
        6.23058707e-307],
       [2.22522597e-306, 1.33511969e-306, 1.37962320e-306,
        9.34604358e-307],
       [9.79101082e-307, 1.78020576e-306, 1.69119873e-306,
        2.22522868e-306],
       [1.24611809e-306, 8.06632139e-308, 1.60221208e-306,
        2.29178686e-312]])

In [36]:
np.full((4,4),4)

array([[4, 4, 4, 4],
       [4, 4, 4, 4],
       [4, 4, 4, 4],
       [4, 4, 4, 4]])

In [38]:
np.full((4,4),5)

array([[5, 5, 5, 5],
       [5, 5, 5, 5],
       [5, 5, 5, 5],
       [5, 5, 5, 5]])

In [31]:
np.random.random((4,5))

array([[0.13083031, 0.4112599 , 0.21545615, 0.50854544, 0.77684107],
       [0.84107302, 0.38675779, 0.42421871, 0.97766704, 0.73702645],
       [0.86491729, 0.78965358, 0.8945919 , 0.72274682, 0.52924074],
       [0.5994882 , 0.98777876, 0.20547765, 0.74914671, 0.4072856 ]])

In [32]:
np.random.randint(1,10)

3

In [39]:
np.random.randint(1,10,size=(3,4))

array([[1, 9, 8, 3],
       [3, 1, 5, 4],
       [9, 8, 3, 1]])

In [41]:
np.random.random()

0.034972346665030685

In [44]:
np.random.randn()

-0.02851804382862997

In [124]:
# import random

In [125]:
np.random.randn(2,4)

array([[ 2.28546707, -1.14907234,  0.21725966, -0.31748464],
       [ 1.47304796, -0.92731528, -1.17544106, -1.0004404 ]])

In [126]:
np.random.rand()

0.3001920856751217

In [127]:
np.random.randint(1000,9999)

8399

In [128]:
np.random.randint(100,999,size=(3,4))

array([[460, 567, 513, 441],
       [442, 994, 451, 259],
       [944, 513, 464, 431]])

In [129]:
np.zeros((2,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [130]:
np.arange(1,3)


array([1, 2])

In [131]:
a.shape

(16,)

In [132]:
# a.shape=(4,4)
# a
            

In [133]:
# a.reshape((2,1,1,2,4))

In [134]:
# a.reshape((4,2,1,1,2))

In [135]:
# a.resize((2,2,4))
#  resize is equal to shape

In [136]:
# a.resize(a,(4,2)

In [137]:
# a.T

In [138]:
# np.transpose(a)

In [139]:
b.T,np.transpose(a)

(array([101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112, 113,
        114, 115, 116]),
 array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16]))

In [140]:
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16])

In [141]:
# a.shape=(4,1,2,1,1,2)


In [142]:
b

array([101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112, 113,
       114, 115, 116])

In [143]:
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16])

In [144]:
# np.swapaxes(a,0,2).shape

In [145]:
# np.rollaxis(a,5,0).shape

In [146]:
b.flatten()  # convert 1d  or np.ravel(a)

array([101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112, 113,
       114, 115, 116])

In [147]:
# list(b.flat)

In [148]:
np.ravel(b)

array([101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112, 113,
       114, 115, 116])

In [149]:
# for i in b.flat:

In [150]:
s=a.flat
next(s)

1

In [151]:
# b[::-1,::3]

In [152]:
# a[::-1,::-1]

In [153]:
# b[[0,2,3],::2]

In [154]:
# for even no

In [155]:
a[a%2==0]

array([ 2,  4,  6,  8, 10, 12, 14, 16])

In [156]:
np.nditer(a.flatten())

In [157]:
x=a.flat
next(x),next(x),next(x),next(x)

(1, 2, 3, 4)

In [158]:
g[:,:2]

array([[6.23042070e-307, 4.67296746e-307],
       [2.22522597e-306, 1.33511969e-306],
       [9.79101082e-307, 1.78020576e-306],
       [1.24611809e-306, 8.06632139e-308]])

In [159]:
a[a%2!=0]   # for odd no.

array([ 1,  3,  5,  7,  9, 11, 13, 15])

In [160]:
b=np.arange(100,116)
b.shape=(4,4)
a,b

(array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16]),
 array([[100, 101, 102, 103],
        [104, 105, 106, 107],
        [108, 109, 110, 111],
        [112, 113, 114, 115]]))

In [46]:
for i in np.nditer((a,b),order='C'):
    print(i,end=' ')

(array(1), array(101)) (array(2), array(102)) (array(3), array(103)) (array(4), array(104)) (array(5), array(105)) (array(6), array(106)) (array(7), array(107)) (array(8), array(108)) (array(9), array(109)) (array(10), array(110)) (array(11), array(111)) (array(12), array(112)) (array(13), array(113)) (array(14), array(114)) (array(15), array(115)) (array(16), array(116)) 

In [47]:
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16])

In [48]:
b=b.flatten()
b

array([101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112, 113,
       114, 115, 116])

In [49]:
b

array([101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112, 113,
       114, 115, 116])

In [50]:
a+b

array([102, 104, 106, 108, 110, 112, 114, 116, 118, 120, 122, 124, 126,
       128, 130, 132])

In [51]:
b

array([101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112, 113,
       114, 115, 116])

In [52]:
np.concatenate((a,b),axis=0)

array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110,
       111, 112, 113, 114, 115, 116])

In [168]:
np.stack((a,b))

array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
         14,  15,  16],
       [100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112,
        113, 114, 115]])

In [169]:
# np.vstack((a,b)) 
np.hstack((a,b))

array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16, 100, 101, 102, 103, 104, 105, 106, 107, 108, 109,
       110, 111, 112, 113, 114, 115])

In [170]:
np.split(a,2,axis=0)

[array([1, 2, 3, 4, 5, 6, 7, 8]), array([ 9, 10, 11, 12, 13, 14, 15, 16])]

In [171]:
# np.split(a,2,axis=1)[0].shape

In [172]:
# np.vsplit(a,2)# it works on row and columns vertical row   and  horizontal columns

In [173]:
np.append(a,b,axis=0)

array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16, 100, 101, 102, 103, 104, 105, 106, 107, 108, 109,
       110, 111, 112, 113, 114, 115])

In [174]:
np.insert(a,1,[12,34,56,78],axis=0)

array([ 1, 12, 34, 56, 78,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13,
       14, 15, 16])

In [175]:
np.insert(a,1,[1],axis=0)   #ya to 1 value do ya jitne ka array hai

array([ 1,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16])

In [176]:
np.delete(a,0)

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16])

In [177]:
a=np.array(['a','x','mnop','abc','hello','a','mnop'])
a

array(['a', 'x', 'mnop', 'abc', 'hello', 'a', 'mnop'], dtype='<U5')

In [178]:
np.unique(a,return_counts=True)

(array(['a', 'abc', 'hello', 'mnop', 'x'], dtype='<U5'),
 array([2, 1, 1, 2, 1], dtype=int64))

In [179]:
np.unique(a,return_index=True)

(array(['a', 'abc', 'hello', 'mnop', 'x'], dtype='<U5'),
 array([0, 3, 4, 2, 1], dtype=int64))