
# Numpy Array slicing

In [1]:
import numpy as np

In [2]:
a=np.arange(1,101).reshape(10,10)
a

array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10],
       [ 11,  12,  13,  14,  15,  16,  17,  18,  19,  20],
       [ 21,  22,  23,  24,  25,  26,  27,  28,  29,  30],
       [ 31,  32,  33,  34,  35,  36,  37,  38,  39,  40],
       [ 41,  42,  43,  44,  45,  46,  47,  48,  49,  50],
       [ 51,  52,  53,  54,  55,  56,  57,  58,  59,  60],
       [ 61,  62,  63,  64,  65,  66,  67,  68,  69,  70],
       [ 71,  72,  73,  74,  75,  76,  77,  78,  79,  80],
       [ 81,  82,  83,  84,  85,  86,  87,  88,  89,  90],
       [ 91,  92,  93,  94,  95,  96,  97,  98,  99, 100]])

In [5]:
a[0,0]  # 0 row and 0 column ki first value 

1

In [6]:
a[0,0].ndim

0

In [8]:
a[0]

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [11]:
a[1:]

array([[ 11,  12,  13,  14,  15,  16,  17,  18,  19,  20],
       [ 21,  22,  23,  24,  25,  26,  27,  28,  29,  30],
       [ 31,  32,  33,  34,  35,  36,  37,  38,  39,  40],
       [ 41,  42,  43,  44,  45,  46,  47,  48,  49,  50],
       [ 51,  52,  53,  54,  55,  56,  57,  58,  59,  60],
       [ 61,  62,  63,  64,  65,  66,  67,  68,  69,  70],
       [ 71,  72,  73,  74,  75,  76,  77,  78,  79,  80],
       [ 81,  82,  83,  84,  85,  86,  87,  88,  89,  90],
       [ 91,  92,  93,  94,  95,  96,  97,  98,  99, 100]])

In [12]:
a[:2]

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15, 16, 17, 18, 19, 20]])

In [13]:
a[-1]

array([ 91,  92,  93,  94,  95,  96,  97,  98,  99, 100])

In [14]:
a[-1:]

array([[ 91,  92,  93,  94,  95,  96,  97,  98,  99, 100]])

In [15]:
a[:1]

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10]])

In [16]:
a[:-1]

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15, 16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25, 26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35, 36, 37, 38, 39, 40],
       [41, 42, 43, 44, 45, 46, 47, 48, 49, 50],
       [51, 52, 53, 54, 55, 56, 57, 58, 59, 60],
       [61, 62, 63, 64, 65, 66, 67, 68, 69, 70],
       [71, 72, 73, 74, 75, 76, 77, 78, 79, 80],
       [81, 82, 83, 84, 85, 86, 87, 88, 89, 90]])

In [17]:
a[:-2]

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15, 16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25, 26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35, 36, 37, 38, 39, 40],
       [41, 42, 43, 44, 45, 46, 47, 48, 49, 50],
       [51, 52, 53, 54, 55, 56, 57, 58, 59, 60],
       [61, 62, 63, 64, 65, 66, 67, 68, 69, 70],
       [71, 72, 73, 74, 75, 76, 77, 78, 79, 80]])

In [18]:
a[:,2]

array([ 3, 13, 23, 33, 43, 53, 63, 73, 83, 93])

In [19]:
a[:,3]

array([ 4, 14, 24, 34, 44, 54, 64, 74, 84, 94])

In [20]:
a[:,1:]

array([[  2,   3,   4,   5,   6,   7,   8,   9,  10],
       [ 12,  13,  14,  15,  16,  17,  18,  19,  20],
       [ 22,  23,  24,  25,  26,  27,  28,  29,  30],
       [ 32,  33,  34,  35,  36,  37,  38,  39,  40],
       [ 42,  43,  44,  45,  46,  47,  48,  49,  50],
       [ 52,  53,  54,  55,  56,  57,  58,  59,  60],
       [ 62,  63,  64,  65,  66,  67,  68,  69,  70],
       [ 72,  73,  74,  75,  76,  77,  78,  79,  80],
       [ 82,  83,  84,  85,  86,  87,  88,  89,  90],
       [ 92,  93,  94,  95,  96,  97,  98,  99, 100]])

In [21]:
a[:,:2]

array([[ 1,  2],
       [11, 12],
       [21, 22],
       [31, 32],
       [41, 42],
       [51, 52],
       [61, 62],
       [71, 72],
       [81, 82],
       [91, 92]])

In [22]:
a[:,-1]

array([ 10,  20,  30,  40,  50,  60,  70,  80,  90, 100])

In [23]:
a[:,-1:]

array([[ 10],
       [ 20],
       [ 30],
       [ 40],
       [ 50],
       [ 60],
       [ 70],
       [ 80],
       [ 90],
       [100]])

In [24]:
a[:,:-1]

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9],
       [11, 12, 13, 14, 15, 16, 17, 18, 19],
       [21, 22, 23, 24, 25, 26, 27, 28, 29],
       [31, 32, 33, 34, 35, 36, 37, 38, 39],
       [41, 42, 43, 44, 45, 46, 47, 48, 49],
       [51, 52, 53, 54, 55, 56, 57, 58, 59],
       [61, 62, 63, 64, 65, 66, 67, 68, 69],
       [71, 72, 73, 74, 75, 76, 77, 78, 79],
       [81, 82, 83, 84, 85, 86, 87, 88, 89],
       [91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [25]:
a[:,:-3]

array([[ 1,  2,  3,  4,  5,  6,  7],
       [11, 12, 13, 14, 15, 16, 17],
       [21, 22, 23, 24, 25, 26, 27],
       [31, 32, 33, 34, 35, 36, 37],
       [41, 42, 43, 44, 45, 46, 47],
       [51, 52, 53, 54, 55, 56, 57],
       [61, 62, 63, 64, 65, 66, 67],
       [71, 72, 73, 74, 75, 76, 77],
       [81, 82, 83, 84, 85, 86, 87],
       [91, 92, 93, 94, 95, 96, 97]])

In [26]:
a[:,2:4]

array([[ 3,  4],
       [13, 14],
       [23, 24],
       [33, 34],
       [43, 44],
       [53, 54],
       [63, 64],
       [73, 74],
       [83, 84],
       [93, 94]])

In [ ]:
a[:,]