In [1]:
import numpy as np

In [50]:
a=np.array([[1,312,2,400],[4,555,77,55],[129,4,3,5]])
a

array([[  1, 312,   2, 400],
       [  4, 555,  77,  55],
       [129,   4,   3,   5]])

In [51]:
np.max(a,axis=0)

array([129, 555,  77, 400])

In [52]:
np.min(a,axis=0)

array([1, 4, 2, 5])

In [53]:
np.average(a)

128.91666666666666

In [54]:
# std=standard deviation

In [55]:
np.std(a)

180.6471968291294

In [56]:
np.mean(a,axis=1)

array([178.75, 172.75,  35.25])

In [57]:
# var=variance

In [58]:
np.var(a,axis=0)

array([ 3557.55555556, 50834.88888889,  1233.55555556, 30838.88888889])

In [59]:
x=np.expand_dims(a,2)# .shape,a.shape  #use for dimension expand
x

array([[[  1],
        [312],
        [  2],
        [400]],

       [[  4],
        [555],
        [ 77],
        [ 55]],

       [[129],
        [  4],
        [  3],
        [  5]]])

In [60]:
np.squeeze(x,2).shape

(3, 4)

In [20]:
# np.sin(linspace(1,21,40))

In [21]:
np.ceil(1.0001)

2.0

In [22]:
np.floor(1.99999)

1.0

In [25]:
np.ptp(a)  #peak to peak  max value-min value

554

In [26]:
np.ptp(a,axis=0)

array([128, 551,  75, 395])

In [27]:
# abs=absolute value

In [28]:
np.sort(a)

array([[  1,   2, 312, 400],
       [  4,  55,  77, 555],
       [  3,   4,   5, 129]])

In [29]:
a

array([[  1, 312,   2, 400],
       [  4, 555,  77,  55],
       [129,   4,   3,   5]])

In [30]:
np.sort(a,axis=1)

array([[  1,   2, 312, 400],
       [  4,  55,  77, 555],
       [  3,   4,   5, 129]])

In [31]:
np.sort(a,axis=0,kind='merge')   #quick,heap,merge   by default quick

array([[  1,   4,   2,   5],
       [  4, 312,   3,  55],
       [129, 555,  77, 400]])

In [32]:
np.where(a%2!=0,'odd','even')

array([['odd', 'even', 'even', 'even'],
       ['even', 'odd', 'odd', 'odd'],
       ['odd', 'even', 'odd', 'odd']], dtype='<U4')

In [33]:
a

array([[  1, 312,   2, 400],
       [  4, 555,  77,  55],
       [129,   4,   3,   5]])

In [34]:
import numpy.matlib as ml

In [35]:
ml.matrix(a)

matrix([[  1, 312,   2, 400],
        [  4, 555,  77,  55],
        [129,   4,   3,   5]])

In [36]:
ml.identity(4)

matrix([[1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.],
        [0., 0., 0., 1.]])

In [37]:
ml.eye(4,4)

matrix([[1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.],
        [0., 0., 0., 1.]])

In [38]:
ml.eye(4,4,2)

matrix([[0., 0., 1., 0.],
        [0., 0., 0., 1.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [39]:
ml.eye(4,4,-2)

matrix([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [1., 0., 0., 0.],
        [0., 1., 0., 0.]])

In [40]:
ml.ones((2,2))

matrix([[1., 1.],
        [1., 1.]])

In [41]:
a=np.array([3,6,4])
b=np.array([4,9,8])

In [48]:
sum(a,b)  # total a add then add value +4,9,8

array([17, 22, 21])

In [42]:
np.sqrt(sum((a-b)**2))

5.0990195135927845

In [43]:
np.linalg.norm(a-b)

5.0990195135927845