In [1]:
a=[2,5,4,6,7,8,9]

In [2]:
import numpy as np

In [3]:
b=np.array(a,dtype=np.int16,ndmin=3)

In [4]:
b**2

array([[[ 4, 25, 16, 36, 49, 64, 81]]], dtype=int16)

In [5]:
b.shape,b.dtype,b.itemsize,b.ndim

((1, 1, 7), dtype('int16'), 2, 3)

In [6]:
c=np.arange(1,10,0.1)
c

array([1. , 1.1, 1.2, 1.3, 1.4, 1.5, 1.6, 1.7, 1.8, 1.9, 2. , 2.1, 2.2,
       2.3, 2.4, 2.5, 2.6, 2.7, 2.8, 2.9, 3. , 3.1, 3.2, 3.3, 3.4, 3.5,
       3.6, 3.7, 3.8, 3.9, 4. , 4.1, 4.2, 4.3, 4.4, 4.5, 4.6, 4.7, 4.8,
       4.9, 5. , 5.1, 5.2, 5.3, 5.4, 5.5, 5.6, 5.7, 5.8, 5.9, 6. , 6.1,
       6.2, 6.3, 6.4, 6.5, 6.6, 6.7, 6.8, 6.9, 7. , 7.1, 7.2, 7.3, 7.4,
       7.5, 7.6, 7.7, 7.8, 7.9, 8. , 8.1, 8.2, 8.3, 8.4, 8.5, 8.6, 8.7,
       8.8, 8.9, 9. , 9.1, 9.2, 9.3, 9.4, 9.5, 9.6, 9.7, 9.8, 9.9])

In [7]:
d=np.linspace(1,10,10) # 1 and 10 ke bich me 10 partition karega
d

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [8]:
e=np.logspace(1,10,10,base=2) # 
print(e)
e.shape

[   2.    4.    8.   16.   32.   64.  128.  256.  512. 1024.]


(10,)

In [9]:
2**d

array([   2.,    4.,    8.,   16.,   32.,   64.,  128.,  256.,  512.,
       1024.])

In [10]:
f=np.empty((5,1))
f

array([[1.32145084e-311],
       [1.32145083e-311],
       [1.32145084e-311],
       [1.32145084e-311],
       [0.00000000e+000]])

In [11]:
np.random.random((4,5))

array([[0.28183814, 0.37559841, 0.64005476, 0.83162602, 0.07275286],
       [0.3873918 , 0.76426518, 0.73565477, 0.64340651, 0.49824322],
       [0.76297361, 0.99152548, 0.21364871, 0.56017801, 0.36952339],
       [0.11428027, 0.82340563, 0.69772478, 0.77183856, 0.5114892 ]])

In [12]:
np.random.randint(1,10)

5

In [13]:
np.random.uniform(1,20)

12.530697193382496

In [14]:
np.random.uniform(1,20,(3,4))

array([[14.28471739,  3.24485232,  5.49555644, 16.42535942],
       [16.07224153,  4.24752508,  2.33750908,  3.68493482],
       [15.11333655, 13.22761101,  6.73924834,  4.38407874]])

In [15]:
np.random.choice([1,2,3,4,5],(2,3))

array([[4, 2, 1],
       [5, 3, 2]])

In [16]:
a=[1,2,3,4,5,6]
np.random.shuffle(a)
a

[5, 6, 4, 2, 1, 3]

In [17]:
np.random.sample(10)

array([0.33131843, 0.62436701, 0.19586616, 0.72757717, 0.89095985,
       0.30887771, 0.90970183, 0.04954098, 0.55599722, 0.53223865])

In [18]:
np.random.randint(1,100,size=(2,3))

array([[73, 95, 89],
       [96, 93, 19]])

In [19]:
np.random.randn(3,2)

array([[-0.38479486,  0.1542709 ],
       [-0.24098045,  0.10435028],
       [ 0.61439984, -0.64382109]])

In [20]:
import random
random.randint(10000,100000)

56147

In [21]:
np.ones((2,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [22]:
np.ones((3,4))*2

array([[2., 2., 2., 2.],
       [2., 2., 2., 2.],
       [2., 2., 2., 2.]])

In [23]:
np.full((3,4),5)

array([[5, 5, 5, 5],
       [5, 5, 5, 5],
       [5, 5, 5, 5]])

In [24]:
np.zeros((2,5,4))

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [25]:
a=np.arange(1,17)
a.shape

(16,)

In [26]:
a.shape=(2,2,4)
a.reshape((4,2,1,1,2))

array([[[[[ 1,  2]]],


        [[[ 3,  4]]]],



       [[[[ 5,  6]]],


        [[[ 7,  8]]]],



       [[[[ 9, 10]]],


        [[[11, 12]]]],



       [[[[13, 14]]],


        [[[15, 16]]]]])

In [27]:
a.resize((4,4))

In [28]:
np.resize(a,(2,3))

array([[1, 2, 3],
       [4, 5, 6]])

In [29]:
a.T,np.transpose(a)

(array([[ 1,  5,  9, 13],
        [ 2,  6, 10, 14],
        [ 3,  7, 11, 15],
        [ 4,  8, 12, 16]]), array([[ 1,  5,  9, 13],
        [ 2,  6, 10, 14],
        [ 3,  7, 11, 15],
        [ 4,  8, 12, 16]]))

In [30]:
a.shape=(4,1,2,1,1,2)

In [31]:
np.swapaxes(a,0,3).shape

(1, 1, 2, 4, 1, 2)

In [32]:
np.rollaxis(a,5,0).shape

(2, 4, 1, 2, 1, 1)

In [33]:
a.flatten(),np.ravel(a)

(array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16]),
 array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16]))

In [34]:
np.nditer(a.flatten())

In [35]:
x=a.flat
next(x),next(x),next(x)

(1, 2, 3)

In [36]:
a.shape=(4,4)
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [37]:
a[:,:2]

array([[ 1,  2],
       [ 5,  6],
       [ 9, 10],
       [13, 14]])

In [38]:
a[::2,::2]

array([[ 1,  3],
       [ 9, 11]])

In [39]:
a[[0,2,3],::2]

array([[ 1,  3],
       [ 9, 11],
       [13, 15]])

In [40]:
a[a>4]

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16])

In [41]:
a[a%2!=0]

array([ 1,  3,  5,  7,  9, 11, 13, 15])

In [42]:
b=np.arange(100,116)
b.shape=(4,4)
a,b

(array([[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12],
        [13, 14, 15, 16]]), array([[100, 101, 102, 103],
        [104, 105, 106, 107],
        [108, 109, 110, 111],
        [112, 113, 114, 115]]))

In [43]:
for i in np.nditer((a,b),order='A'):
    print(i,end=' ')

(array(1), array(100)) (array(2), array(101)) (array(3), array(102)) (array(4), array(103)) (array(5), array(104)) (array(6), array(105)) (array(7), array(106)) (array(8), array(107)) (array(9), array(108)) (array(10), array(109)) (array(11), array(110)) (array(12), array(111)) (array(13), array(112)) (array(14), array(113)) (array(15), array(114)) (array(16), array(115)) 

In [44]:
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [45]:
b

array([[100, 101, 102, 103],
       [104, 105, 106, 107],
       [108, 109, 110, 111],
       [112, 113, 114, 115]])

In [46]:
np.concatenate((a,b),axis=1)
np.concatenate((a,b),axis=1).shape

(4, 8)

In [47]:
np.stack((a,b),axis=0).shape

(2, 4, 4)

In [48]:
np.stack((a,b),axis=1)

array([[[  1,   2,   3,   4],
        [100, 101, 102, 103]],

       [[  5,   6,   7,   8],
        [104, 105, 106, 107]],

       [[  9,  10,  11,  12],
        [108, 109, 110, 111]],

       [[ 13,  14,  15,  16],
        [112, 113, 114, 115]]])

In [49]:
np.vstack((a,b)).shape,np.hstack((a,b)).shape

((8, 4), (4, 8))

In [50]:
np.split(a,4,axis=0)

[array([[1, 2, 3, 4]]),
 array([[5, 6, 7, 8]]),
 array([[ 9, 10, 11, 12]]),
 array([[13, 14, 15, 16]])]

In [51]:
np.split(a,4,axis=1)  #[0].shape

[array([[ 1],
        [ 5],
        [ 9],
        [13]]), array([[ 2],
        [ 6],
        [10],
        [14]]), array([[ 3],
        [ 7],
        [11],
        [15]]), array([[ 4],
        [ 8],
        [12],
        [16]])]

In [52]:
np.vsplit(a,2)

[array([[1, 2, 3, 4],
        [5, 6, 7, 8]]), array([[ 9, 10, 11, 12],
        [13, 14, 15, 16]])]

In [53]:
np.hsplit(a,2)

[array([[ 1,  2],
        [ 5,  6],
        [ 9, 10],
        [13, 14]]), array([[ 3,  4],
        [ 7,  8],
        [11, 12],
        [15, 16]])]

In [54]:
np.append(a,b,axis=0).shape

(8, 4)

In [55]:
np.append(a,b,axis=1).shape

(4, 8)

In [56]:
np.insert(a,1,[12,34,56,78],axis=0)

array([[ 1,  2,  3,  4],
       [12, 34, 56, 78],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [57]:
np.insert(a,1,[12,34,56,78],axis=1)

array([[ 1, 12,  2,  3,  4],
       [ 5, 34,  6,  7,  8],
       [ 9, 56, 10, 11, 12],
       [13, 78, 14, 15, 16]])

In [58]:
np.insert(a,1,[12,34,56,78],axis=1).reshape(2,2,5)

array([[[ 1, 12,  2,  3,  4],
        [ 5, 34,  6,  7,  8]],

       [[ 9, 56, 10, 11, 12],
        [13, 78, 14, 15, 16]]])

In [59]:
np.delete(a,0)

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16])

In [60]:
np.delete(a,0,axis=0)

array([[ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [61]:
np.delete(a,0,axis=1)

array([[ 2,  3,  4],
       [ 6,  7,  8],
       [10, 11, 12],
       [14, 15, 16]])

In [62]:
a=np.array(['a','x','a','mnop','abc','hello','a','mnop'])

In [63]:
np.unique(a)

array(['a', 'abc', 'hello', 'mnop', 'x'], dtype='<U5')

In [64]:
np.unique(a,return_counts=True)

(array(['a', 'abc', 'hello', 'mnop', 'x'], dtype='<U5'),
 array([3, 1, 1, 2, 1], dtype=int64))

In [65]:
np.unique(a,return_index=True)

(array(['a', 'abc', 'hello', 'mnop', 'x'], dtype='<U5'),
 array([0, 4, 5, 3, 1], dtype=int64))

In [66]:
np.unique(a,return_inverse=True)

(array(['a', 'abc', 'hello', 'mnop', 'x'], dtype='<U5'),
 array([0, 4, 0, 3, 1, 2, 0, 3], dtype=int64))

In [67]:
a

array(['a', 'x', 'a', 'mnop', 'abc', 'hello', 'a', 'mnop'], dtype='<U5')

In [68]:
a=np.array([[1,312,2,400],[4,555,77,55],[129,4,3,5]])

In [69]:
a

array([[  1, 312,   2, 400],
       [  4, 555,  77,  55],
       [129,   4,   3,   5]])

In [70]:
np.max(a,axis=0)

array([129, 555,  77, 400])

In [71]:
np.max(a,axis=1)

array([400, 555, 129])

In [72]:
np.min(a,axis=0),np.min(a,axis=1)

(array([1, 4, 2, 5]), array([1, 4, 3]))

In [73]:
np.mean(a),np.mean(a,axis=0),np.mean(a,axis=1)

(128.91666666666666,
 array([ 44.66666667, 290.33333333,  27.33333333, 153.33333333]),
 array([178.75, 172.75,  35.25]))

In [74]:
np.average(a),np.average(a,axis=0),np.average(a,axis=1)

(128.91666666666666,
 array([ 44.66666667, 290.33333333,  27.33333333, 153.33333333]),
 array([178.75, 172.75,  35.25]))

In [75]:
np.std(a,axis=0)

array([ 59.64524755, 225.46593731,  35.12200956, 175.6100478 ])

In [76]:
x=np.expand_dims(a,2)
x.shape

(3, 4, 1)

In [77]:
np.squeeze(x,2).shape

(3, 4)

In [78]:
np.around(np.sin(np.linspace(1,21,40)))

array([ 1.,  1.,  1.,  1.,  0., -0., -1., -1., -1., -1., -0.,  0.,  1.,
        1.,  1.,  1.,  0., -0., -1., -1., -1., -1., -0.,  0.,  1.,  1.,
        1.,  1.,  0., -0., -1., -1., -1., -1., -0.,  0.,  1.,  1.,  1.,
        1.])

In [79]:
np.ceil(1.00001)

2.0

In [80]:
np.floor(1.9999)

1.0

In [81]:
a

array([[  1, 312,   2, 400],
       [  4, 555,  77,  55],
       [129,   4,   3,   5]])

In [82]:
np.ptp(a,axis=0)

array([128, 551,  75, 395])

In [83]:
np.ptp(a,axis=1)

array([399, 551, 126])

In [84]:
np.sort(a,axis=0,kind='heap')

array([[  1,   4,   2,   5],
       [  4, 312,   3,  55],
       [129, 555,  77, 400]])

In [85]:
a

array([[  1, 312,   2, 400],
       [  4, 555,  77,  55],
       [129,   4,   3,   5]])

In [86]:
np.where(a%2!=0,'odd','even')
# np.where(a%2!=0,"b")

array([['odd', 'even', 'even', 'even'],
       ['even', 'odd', 'odd', 'odd'],
       ['odd', 'even', 'odd', 'odd']], dtype='<U4')

In [87]:
import numpy.matlib as ml

In [88]:
a=ml.matrix(a)

In [89]:
a

matrix([[  1, 312,   2, 400],
        [  4, 555,  77,  55],
        [129,   4,   3,   5]])

In [90]:
ml.identity(4)

matrix([[1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.],
        [0., 0., 0., 1.]])

In [91]:
ml.eye(4,5,-2)

matrix([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.]])

In [92]:
ml.ones((2,2))

matrix([[1., 1.],
        [1., 1.]])

In [93]:
ml.zeros((2,2))

matrix([[0., 0.],
        [0., 0.]])

In [94]:
a=np.array([3,6,4])
b=np.array([4,9,8])


In [95]:
np.sqrt(sum((a-b)**2))

5.0990195135927845

In [96]:
np.linalg.norm(a-b) #use for distance calculate

5.0990195135927845

In [97]:
np.sqrt(sum((a-b)**2))

5.0990195135927845

In [98]:
a=np.array([[1,2,3],[2,3,4],[5,6,7]])
b=np.array([[1,2,3],[2,3,4],[5,6,7]])

In [99]:
print(a)

[[1 2 3]
 [2 3 4]
 [5 6 7]]


In [100]:
print(b)

[[1 2 3]
 [2 3 4]
 [5 6 7]]


In [101]:
b.ndim

2

In [102]:
a.shape

(3, 3)

In [103]:
b.shape

(3, 3)

In [104]:
a.dot(b)

array([[20, 26, 32],
       [28, 37, 46],
       [52, 70, 88]])

In [105]:
np.dot(a,b)

array([[20, 26, 32],
       [28, 37, 46],
       [52, 70, 88]])

In [106]:
np.matmul(a,b)

array([[20, 26, 32],
       [28, 37, 46],
       [52, 70, 88]])

In [107]:
import numpy.matlib as ml

In [108]:
s=ml.matrix([[1,2,3,4,5],[2,3,4,5,6],[2,3,4,5,6]])

In [109]:
d=ml.matrix([[1,2,3,4,5],[2,3,4,5,6],[2,3,4,5,6]])

In [110]:
s.shape,d.shape

((3, 5), (3, 5))

In [111]:
a=np.array([[6,1,1],[4,-2,5],[2,8,7]])

In [112]:
a

array([[ 6,  1,  1],
       [ 4, -2,  5],
       [ 2,  8,  7]])

### rank of matrix

In [113]:
np.linalg.matrix_rank(a)

3

# trace of matrix

In [116]:
np.trace(a)

11

## determinant of matrix

In [117]:
np.linalg.det(a)

-306.0

### inverse of matrix

In [118]:
np.linalg.inv(a)

array([[ 0.17647059, -0.00326797, -0.02287582],
       [ 0.05882353, -0.13071895,  0.08496732],
       [-0.11764706,  0.1503268 ,  0.05228758]])

# eigen value

In [120]:
a,b=np.linalg.eig(a)

In [121]:
a

array([11.24862343,  5.09285054, -5.34147398])

In [122]:
b

array([[ 0.24511338,  0.75669314,  0.02645665],
       [ 0.40622202, -0.03352363, -0.84078293],
       [ 0.88028581, -0.65291014,  0.54072554]])