# count vectorizer

## word count with count vectorizer

In [42]:
from sklearn.feature_extraction.text import CountVectorizer

In [43]:
text=['the quick brown fox jumped over the lazy dog']

In [44]:
vectorizer=CountVectorizer()

In [45]:
vectorizer.fit(text)

CountVectorizer(analyzer='word', binary=False, decode_error='strict',
        dtype=<class 'numpy.int64'>, encoding='utf-8', input='content',
        lowercase=True, max_df=1.0, max_features=None, min_df=1,
        ngram_range=(1, 1), preprocessor=None, stop_words=None,
        strip_accents=None, token_pattern='(?u)\\b\\w\\w+\\b',
        tokenizer=None, vocabulary=None)

In [46]:
print(vectorizer.vocabulary_)

{'the': 7, 'quick': 6, 'brown': 0, 'fox': 2, 'jumped': 3, 'over': 5, 'lazy': 4, 'dog': 1}


In [47]:
vector=vectorizer.transform(text)

In [48]:
print(vector.shape)
print(type(vector))
print(vector.toarray())
print(vectorizer.vocabulary_)

(1, 8)
<class 'scipy.sparse.csr.csr_matrix'>
[[1 1 1 1 1 1 1 2]]
{'the': 7, 'quick': 6, 'brown': 0, 'fox': 2, 'jumped': 3, 'over': 5, 'lazy': 4, 'dog': 1}


### encode another documents

In [49]:
text2=['the puppy']

In [50]:
vector=vectorizer.transform(text2)

In [51]:
print(vector.toarray())

[[0 0 0 0 0 0 0 1]]


# Tfidf vectorizer

## word frequencies with tfidf

In [52]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [61]:
text2=['the quick brown fox jumped over the lazy dog']

In [62]:
vectorize=TfidfVectorizer()

In [63]:
vectorize.fit(text2)

TfidfVectorizer(analyzer='word', binary=False, decode_error='strict',
        dtype=<class 'numpy.float64'>, encoding='utf-8', input='content',
        lowercase=True, max_df=1.0, max_features=None, min_df=1,
        ngram_range=(1, 1), norm='l2', preprocessor=None, smooth_idf=True,
        stop_words=None, strip_accents=None, sublinear_tf=False,
        token_pattern='(?u)\\b\\w\\w+\\b', tokenizer=None, use_idf=True,
        vocabulary=None)

In [64]:
print(vectorize.vocabulary_)

{'the': 7, 'quick': 6, 'brown': 0, 'fox': 2, 'jumped': 3, 'over': 5, 'lazy': 4, 'dog': 1}


In [65]:
print(vectorize.idf_)

[1. 1. 1. 1. 1. 1. 1. 1.]


In [67]:
vector=vectorize.transform([text2[0]])

In [68]:
print(vector.shape)

(1, 8)


In [69]:
print(vector.toarray())

[[0.30151134 0.30151134 0.30151134 0.30151134 0.30151134 0.30151134
  0.30151134 0.60302269]]
