In [4]:
import pandas as pd
import numpy as np

In [5]:
dt=pd.read_csv('ucicancer.csv')

In [6]:
dt.columns

Index(['Unnamed: 0', 'a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j',
       'class'],
      dtype='object')

In [7]:
dt.dtypes

Unnamed: 0     int64
a              int64
b              int64
c              int64
d              int64
e              int64
f              int64
g             object
h              int64
i              int64
j              int64
class          int64
dtype: object

In [8]:
# dt.dtypes
# dt.g=dt.g.replace('?',15)
# dt.g=dt.g.astype(dtype=np.int64)

In [9]:
dt=dt.replace("?",15)
dt=dt[['b','c','d','f','g','h','i','j','class']]
# a ko remove karna hai

In [10]:
dt['g']=dt['g'].astype(dtype='i')
x=dt.drop('class',axis=1)
y=np.where(dt['class']==2,1,0)



In [11]:
from sklearn.model_selection import train_test_split
x_tr,x_ts,y_tr,y_ts=train_test_split(x,y,test_size=0.2)


In [12]:
from sklearn.linear_model import LogisticRegression
algo=LogisticRegression()
algo.fit(x_tr,y_tr)
algo.score(x_ts,y_ts)

C:\Users\hp\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


0.95

In [13]:
from sklearn.metrics import confusion_matrix
print(confusion_matrix(y_ts,algo.predict(x_ts)))
# prediction ke hisab batayega

[[43  3]
 [ 4 90]]


In [14]:
from sklearn.metrics import classification_report
print(classification_report(y_ts,algo.predict(x_ts)))
# % ke hisab se batayega

              precision    recall  f1-score   support

           0       0.91      0.93      0.92        46
           1       0.97      0.96      0.96        94

   micro avg       0.95      0.95      0.95       140
   macro avg       0.94      0.95      0.94       140
weighted avg       0.95      0.95      0.95       140



In [15]:
def sigmoid(z):
    return 1/(1+np.exp(-z))

In [16]:
x_tr.shape,x_tr.iloc[0].values.shape

((558, 8), (8,))

In [17]:
x_tr.shape

(558, 8)

In [18]:
x_tr.shape

(558, 8)

In [19]:
th=np.zeros((1,x_tr.shape[1])) #main zeros array banaunga jisme main x_tr.shape[1] means column ka shape lunga.

In [20]:
x_tr.iloc[0]

b     5
c     3
d     5
f     3
g     3
h     4
i    10
j     1
Name: 59, dtype: int64

In [21]:
th*x_tr.iloc[0].values

array([[0., 0., 0., 0., 0., 0., 0., 0.]])

In [22]:
x_tr

b   c   d   f   g   h   i  j
59    5   3   5   3   3   4  10  1
572   1   1   1   2   1   2   1  1
515   1   1   1   1   1   1   1  1
464  10   9   8   6   4   7  10  3
255   3   1   1   2   1   1   1  1
660   4   1   1   2   1   3   1  1
263   7   9   4  10   3   5   3  3
633   3   1   1   2   1   1   1  1
613   2   1   1   1   1   2   1  1
140   2   1   1   2   1   1   1  1
229   7   4   7   3   7   7   6  1
676   5   1   1   2   1   1   1  1
83    3   5   7   8   9   7  10  7
207   1   1   1   1   1   3   1  1
315   5   5   5   5  10   4   3  1
312   1   1   1   2   1   1   1  1
447   1   1   1   1   1   1   1  1
344   1   1   1   2   1   1   1  1
455  10   6   5   5  10   8   6  1
270   5   1   1   2   1   3   1  1
68    1   1   1   2   1   3   2  1
43   10  10  10   8   1   8  10  1
381   3   2   2   2   1   3   2  1
684   1   1   1   2   1   1   1  1
365   6  10  10   8  10   7  10  7
342   1   1   1   2   1   1   1  1
159  10   7   7   5  10   5   7  2
92    1   1   1   2   1   2   1  1
628   4   1   1   2   1   1   1  1
23    1   1   1   2   1   3   1  1
..   ..  ..  ..  ..  ..  ..  .. ..
295   5   3   4   4   5   4   7  1
458   5   1   3   2   1   1   1  1
277   1   1   1   2   1   3   1  1
479   5   1   1   1   1   1   1  1
198   3   1   1   2   1   2   1  1
519   1   1   1   3   1   1   1  1
230   6   8   7   6   8   8   9  2
532   3   1   1   2   1   2   1  1
387   2   1   1   2   1   2   2  1
599   3   1   1   2   1   2   1  1
439  10   4   3   4  10  10   1  1
144   1   1   3   2  15   2   1  1
454  10   2   2   2   6   1   1  2
302   1   1   1   2   1   3   1  1
453   2   3   1   3   1   1   1  1
138   1   1   1   1  15   2   1  1
518   4   7   8   4  10   9   1  1
396   4   1   1   2   1   1   1  1
620   6   3   3   3   2   6   1  1
357   8  10   5   8   4   4  10  3
413   8   5   6   3  10   6   6  1
40   10   4   3   3   3   6   5  2
228  10  10  10  10  10   9  10  1
634   3   1   4   2   1   1   1  1
12    1   1   1   2   3   3   1  1
580   5   7  10   5  10   7   5  1
507   5   1   1   2   1   1   1  1
242   1   1   1   2   5   5   1  1
340   1   1   1   2   1   3   1  1
117   1   1   1   4   3   1   1  1

[558 rows x 8 columns]

In [23]:
# np.matmul(th,x_tr.iloc[0].value)

In [24]:
np.matmul(th,x_tr.T)

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 

In [25]:
th=np.zeros((1,x_tr.shape[1]))

In [26]:
import numpy.matlib as ml
def cost(x,y,th):
    t=ml.matrix(th)
    xm=ml.matrix(x)
    s=sigmoid(t*xm.T)
    first=y*np.array(np.log(s))
    second=(1-y)*np.array(np.log(1-s))
    return -1*(first+second).mean()
cost(x_tr,y_tr,th)

0.6931471805599453

In [27]:
def gradient(x,y,th):
    t=ml.matrix(th)
    xm=ml.matrix(x)
    s=sigmoid(th*xm.T)
#     print(x.shape)
    err=s-y
    return err.shape
    

In [28]:
gradient(x_tr,y_tr,th)

(1, 558)

In [29]:
def gradient(x,y,th):
    t=ml.matrix(th)
    xm=ml.matrix(x)
    s=sigmoid(th*xm.T)
#     print(x.shape)
    err=s-y
    n=np.array(x)*np.array(err).T
    th=th-0.001*n.mean(axis=0)
    return th
    

In [30]:
gradient(x_tr,y_tr,th)

array([[-0.00030018, -0.00070878, -0.00065054, -0.00023208, -0.00077151,
        -0.00036738, -0.00062993, -0.00012903]])

In [31]:
cost(x_tr,y_tr,gradient(x_tr,y_tr,th))

0.6909658258201793

In [32]:
for i in range(1000):
    th=gradient(x_tr,y_tr,th)
    if i%10==0:
        print(cost(x_tr,y_tr,th))

0.6909658258201793
0.6747705674487026
0.665116554174828
0.6588249867651267
0.6542966907111818
0.6507198598245202
0.6476748016044489
0.6449402407516777
0.6423973324959666
0.6399811307736623
0.6376555263095212
0.6354000542128442
0.6332028354820134
0.6310567494497539
0.6289573356723742
0.6269016338452228
0.6248875379345473
0.6229134346006724
0.6209779998542705
0.6190800842485634
0.6172186478131132
0.6153927230211708
0.6136013935930005
0.6118437822594628
0.6101190436007251
0.6084263597610917
0.6067649377940354
0.60513400793128
0.6035328223758896
0.6019606543930234
0.6004167975706263
0.59890056517824
0.5974112895838126
0.5959483217062733
0.5945110304917128
0.5930988024066377
0.5917110409448878
0.5903471661464997
0.5890066141277152
0.587688836621791
0.5863933005305025
0.5851194874863115
0.5838668934252128
0.5826350281702536
0.5814234150257046
0.5802315903818301
0.5790591033301836
0.5779055152893189
0.5767703996407993
0.5756533413753538
0.5745539367490233
0.5734717929491214
0.5724065277698281

In [33]:
def predict(x,th):
    t=ml.matrix(th)
    xm=ml.matrix(x)
    s=sigmoid(th*xm.T)
    if s>=0.5:
        return 1
    else:
        return 0
    

In [34]:
c=0
for i in range(x_ts.shape[0]):
    if predict (x_ts.iloc[i],th)==y_ts[i]:
        c+=1
c/x_ts.shape[0]
#accuracy check 

0.8571428571428571