In [1]:
import numpy as np
a=np.arange(1,7)
a.shape=(3,2)
c=np.mean(a.T,axis=1)
d=a-c
e=np.cov(d.T)
val,vect=np.linalg.eig(e)
vect.T.dot(d.T)


array([[-2.82842712,  0.        ,  2.82842712],
       [ 0.        ,  0.        ,  0.        ]])

In [5]:
from sklearn.decomposition.pca import PCA
alg=PCA(2)
alg.fit(a)
alg.transform(a)

array([[ -2.82842712e+00,  -2.22044605e-16],
       [  0.00000000e+00,   0.00000000e+00],
       [  2.82842712e+00,   2.22044605e-16]])

In [17]:
a=np.arange(1,7)
a.shape=(3,2)
c=np.mean(a,axis=0)
d=a-c
m=np.cov(d.T)
val,vect=np.linalg.eig(m)
vect.T.dot(d.T)

array([[-2.82842712,  0.        ,  2.82842712],
       [ 0.        ,  0.        ,  0.        ]])

In [16]:
alg.components_,alg.explained_variance_

(array([[ 0.70710678,  0.70710678],
        [-0.70710678,  0.70710678]]), array([ 8.,  0.]))

array([[6.66666667, 6.66666667],
       [6.66666667, 6.66666667]])

array([6.36396103, 0.70710678])